version = 3.9.4
runner.dialect = scala3

maxColumn = 100
indent.main = 2
indent.callSite = 2
indent.defnSite = 2

align.preset = more
align.openParenCallSite = false
align.openParenDefnSite = false

newlines.topLevelStatementBlankLines = [
  { blanks { before = 1 } }
]

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]

rewrite.sortModifiers.order = [
  "override", "private", "protected", "final",
  "sealed", "abstract", "implicit", "lazy"
]

docstrings.style = Asterisk
docstrings.oneline = keep
