services:
  api1:
    image: ghcr.io/devgabrielsborges/rinha-2026-scala:latest
    hostname: api1
    environment:
      - DATA_DIR=/app/data
      - INDEX_DIR=/app/index
      - IVF_NPROBE=5
      - HTTP_PORT=8080
      - HTTP_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165MB"

  api2:
    image: ghcr.io/devgabrielsborges/rinha-2026-scala:latest
    hostname: api2
    environment:
      - DATA_DIR=/app/data
      - INDEX_DIR=/app/index
      - IVF_NPROBE=5
      - HTTP_PORT=8080
      - HTTP_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165MB"

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"
